### ISSUE TITLE
Death Messages

### ISSUE THREAD

**Issue by Wertzui123** [tim03we/AdvancedJoin#2]
Jo ist nice, besser als CustomAlerts, aber können sie auch noch die ganzen Death Messages einstellbar machen? Dass passt zwar nicht zum Plugin, aber dann wäre es für mich eine bessere Version von CustomAlerts!

Viele Grüße,
Wertzui123

**Comment by tim03we** [comment]
Wäre möglich, vllt. abseits der settings.yml mit einer anderen Config, mal sehen was sich da machen lässt.

**Comment by Wertzui123** [comment]
Ok Super

**Comment by Wertzui123** [comment]
Ach und die ganzen anderen Messages wie "Server Veraltert" ändern zu können wäre auch nice!
